name: iOS Tests CI

on:
  push:
    branches:
      - ci

jobs:
  test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          path: .

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar Appium
        run: npm install -g appium

      - name: Iniciar Appium em background
        run: |
          appium --base-path /wd/hub &
          sleep 15

      - name: Executar testes no Appium local
        run: npx wdio
